name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message
        run: echo "Hello, world! Une modification a été poussée ou une PR a été ouverte."